openapi: "3.0.3"
info:
  title: OpenAPI spesifikasjon for tilgjengeliggjøring av reelle rettighetshavere
  description: OpenAPI spesifikasjon for tilgjengeliggjøring av reelle rettighetshavere. APIet krever maskinporten-token. Gyldige scopes er brreg:reelle/partner.offentlig for offentlig myndighet, og brreg:reelle/partner.rapporteringspliktig for viksomheter som er rapporteringspliktig etter hvitevaskingsloven.
  version: "0.3"

paths:
  /rrh/api/reelle-rettighetshavere/{organisasjonsnummer}:
    summary: Hent ut reell rettighet basert på organisasjonsnummer for registreringspliktig virksomhet
    description: Hent ut reell rettighet basert på organisasjonsnummer for registreringspliktig virksomhet.

    get:
      tags:
        - reelle rettigheter
      summary: Hent ut reell rettighet basert på organisasjonsnummer for registreringspliktig virksomhet
      description: Hent ut reell rettighet basert på organisasjonsnummer for registreringspliktig virksomhet
      operationId: hentReellRettighet
      parameters:
        - name: organisasjonsnummer
          in: path
          description: Organisasjonsnummer til den registreringspliktige virksomheten
          required: true
          schema:
            $ref: '#/components/schemas/Organisasjonsnummer'
      responses:
        '200':
          $ref: '#/components/responses/200'
        '400':
          $ref: '#/components/responses/400'
        '403':
          $ref: '#/components/responses/403'
        '404':
          $ref: '#/components/responses/404'
        '500':
          $ref: '#/components/responses/500'
      security:
        - bearerAuth: []

components:
  schemas:
    ReellRettighet:
      type: object
      properties:
        registreringId:
          type: string
          example: 'd3877b48-a4fb-4949-86e1-be4645771147'
        registreringStatus:
          $ref: '#/components/schemas/RegistreringStatus'
        gjelderFraDato:
          $ref: '#/components/schemas/DatoKlokkeslett'
        reelleRettighetshavereStatus:
          $ref: '#/components/schemas/ReelleRettighetshavereStatus'
        reelleRettighetshavere:
          $ref: '#/components/schemas/ReelleRettighetshavere'
    RegistreringStatus:
      type: object
      properties:
        kode:
          type: string
          example: registreringstatus.regi
        beskrivelse:
          type: string
          example: Registrert
    DatoKlokkeslett:
      type: string
      #pattern: \d{4}-(?:0[1-9]|1[0-2])-(?:0[1-9]|[1-2]\d|3[0-1])T(?:[0-1]\d|2[0-3]):[0-5]\d:[0-5]\d(?:\.\d+|)(?:Z|(?:\+|\-)(?:\d{2}):?(?:\d{2}))
      example: '2022-02-14T09:13:45.12Z'
    ReelleRettighetshavereStatus:
      type: object
      properties:
        kode:
          type: string
          example: reellerettighetshaverestatus.nrki
        beskrivelse:
          type: string
          example: Noen reelle rettighetshavere kan ikke identifiseres
    Organisasjonsnummer:
      type: string
      example: 974760673
    ReelleRettighetshavere:
      type: array
      items:
        $ref: '#/components/schemas/ReellRettighetshaver'
    ReellRettighetshaver:
      type: object
      properties:
        foedselsdato:
          type: string
          example: '1999-08-02'
        foedselsaar:
          type: string
          example: '1999'
        navn:
          $ref: '#/components/schemas/Navn'
        foerstRegistrertDato:
          $ref: '#/components/schemas/DatoKlokkeslett'
        endretDato:
          $ref: '#/components/schemas/DatoKlokkeslett'
        statsborgerskap:
          type: array
          items:
            $ref: '#/components/schemas/LandOgKode'
        bostedsland:
          $ref: '#/components/schemas/LandOgKode'
        erDoed:
          type: boolean
          example: false
        erUnntattFraInnsyn:
          type: boolean
          example: false
        posisjoner:
          type: array
          items:
            $ref: '#/components/schemas/Posisjon'
    LandOgKode:
      type: object
      properties:
        landkode:
          type: string
          example: NO
        land:
          type: string
          example: Norge
    Navn:
      type: object
      properties:
        fornavn:
          type: string
          example: PUSSIG LAV
        mellomnavn:
          type: string
          example: DAL
        etternavn:
          type: string
          example: JORDBÆR
        fulltNavn:
          type: string
          example: PUSSIG LAV DAL JORDBÆR
    Posisjon:
      type: object
      properties:
        posisjonType:
          $ref: '#/components/schemas/PosisjonType'
        stoerrelseIntervall:
          $ref: '#/components/schemas/StoerrelseIntervall'
        grunnlag:
          type: array
          items:
            $ref: '#/components/schemas/Grunnlag'
        beskrivelseAnnenMaate:
          type: string
          example: Fritekst som beskriver hvordan rettighetshaveren har kontroll i virksomheten
    StoerrelseIntervall:
      type: object
      properties:
        kode:
          type: string
          example: stoerrelseintervall.int1
        beskrivelse:
          type: string
          example: 25,01% - 49,99%
    PosisjonType:
      type: object
      properties:
        kode:
          type: string
          example: posisjontype.eier
        beskrivelse:
          type: string
          example: Eierskap
    Grunnlag:
      type: object
      properties:
        grunnlagType:
          $ref: '#/components/schemas/GrunnlagType'
    GrunnlagType:
      type: object
      properties:
        kode:
          type: string
          example: grunnlagtype.dire
        beskrivelse:
          type: string
          example: Direkte
    ServerErrorResponse:
      type: object
      properties:
        timestamp:
          $ref: '#/components/schemas/DatoKlokkeslett'
        status:
          type: integer
          example: 500
        error:
          type: string
          example: Internal Server Error
        message:
          type: string
          example: Houston we have a problem!
        path:
          type: string
          example: /rrh/api/reellerettigheter/974760673
        trace:
          type: string
          example: 5631709a-6e3e-4b72-94e7-fcbf6341272a

  responses:
    200:
      description: Hent ut reell rettighet basert på organisasjonsnummer for registreringspliktig virksomhet
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ReellRettighet'
        application/hal+json:
          schema:
            $ref: '#/components/schemas/ReellRettighet'
    400:
      description: Feilaktig forespørsel, grunnet organisasjonsnummer med ugyldige tegn eller lengde
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ServerErrorResponse'
          examples:
            BadRequestResponse:
              $ref: '#/components/examples/BadRequestResponse'
    403:
      description: Det mangler eller er feil på maskinporten token
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ServerErrorResponse'
          examples:
            TokenVerificationFailedResponse:
              $ref: '#components/examples/TokenVerificationFailedResponse'

    404:
      description: Virksomheten er ikke registreringspliktig i register over reelle rettighetshavere
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ServerErrorResponse'
          examples:
            NotFoundResponse:
              $ref: '#/components/examples/NotFoundResponse'
    500:
      description: Uventet feil på tjenesten
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ServerErrorResponse'
          examples:
            InternalServerErrorResponse:
              $ref: '#/components/examples/InternalServerErrorResponse'

  examples:
    BadRequestResponse:
      summary: 400 Ugyldig organisasjonsnummer
      value:
        type: Ugyldig respons
        status: 400
        error: Bad Request
        message: Organisasjonsnummer må være et nummer med nøyaktig ni siffer
        path: /rrh/api/reellerettigheter/974760
        timestamp: '2022-02-14T09:13:45.12Z'
    TokenVerificationFailedResponse:
      summary: 403 Ugyldig token
      value:
        type: Ugyldig token
        status: 403
        error: Forbidden
        message: Du har ikke tilgang til dette APIet
        path: /rrh/api/reellerettigheter/974760673
        timestamp: '2022-02-14T09:13:45.12Z'
    NotFoundResponse:
      summary: 404 Ikke funnet
      value:
        type: Ikke funnet
        status: 404
        error: Not Found
        message: Virksomheten er ikke registreringspliktig i register over reelle rettighetshavere
        path: /rrh/api/reellerettigheter/974760673
        timestamp: '2022-02-14T09:13:45.12Z'
    InternalServerErrorResponse:
      summary: 500 Intern feil
      value:
        type: Intern feil
        status: 500
        error: Internal Server Error
        message: Uventet feil på tjenesten. Vennligst prøv igjen senere, eller kontakt oss om problemet vedvarer
        path: /rrh/api/reellerettigheter/974760673
        timestamp: '2022-02-14T09:13:45.12Z'
